### ISSUE TITLE
Kunena Discuss 3.0 - Error when topic is deleted

### ISSUE THREAD

**Issue by GJSchaller** [Kunena/Kunena-Addons#131]
If an article creates a thread, and then that thread is deleted, the Discuss plugin throws an error on that article:

"Warning: Invalid argument supplied for foreach() in /home/(site)/public_html/libraries/kunena/forum/message/helper.php on line 234"

Preferred behavior should be that it re-creates a (new) thread, or maybe an option to not make a thread if desired / set by Admin.

**Comment by 810** [comment]
The topic is closed until you perm delete the topic. If the topic is gone, the reply box is showed again. I'm closing this one
