### ISSUE TITLE
Kunena Login does not work if you set Direct Component Access = No

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Addons#149]
Joomla 2.5 Debug message:
Call stack
    Function    Location
1   JSite->dispatch()   JROOT/index.php:42
2   JComponentHelper::renderComponent() JROOT/includes/application.php:197
3   JComponentHelper::executeComponent()    JROOT/libraries/joomla/application/component/helper.php:351
4   require_once()  JROOT/libraries/joomla/application/component/helper.php:383
5   JError::raiseError()    JROOT/components/com_kunena/kunena.php:36
6   JError::raise() JROOT/libraries/joomla/error/error.php:251

Joomla 3.1 Debug message:
Call stack
    Function    Location
1   JSite->dispatch()   JROOT/index.php:52
2   JComponentHelper::renderComponent() JROOT/includes/application.php:221
3   JComponentHelper::executeComponent()    JROOT/libraries/legacy/component/helper.php:339
4   require_once()  JROOT/libraries/legacy/component/helper.php:359
5   JError::raiseError()    JROOT/components/com_kunena/kunena.php:36
6   JError::raise() JROOT/libraries/legacy/error/error.php:242

**Comment by deqsec** [comment]
Just comment this rows:




And paste this rows after:
<input type="hidden" name="option" value="com_users">
<input type="hidden" name="task" value="user.logout">

or (if login): <input type="hidden" name="task" value="user.login">
