### ISSUE TITLE
Discuss: Wrong post number is shown in the article view

### ISSUE THREAD

**Issue by chang-zhao** [Kunena/Kunena-Addons#155]
![discuss_error_1](https://f.cloud.github.com/assets/5161535/1049214/46e98b74-109e-11e3-8706-2a30532cdc46.jpg)
In the forum thread view, comments to the article are numbered #1 (= link to the article), then #2, #3 etc.
But on the page (= in the article view), instead of #2, #3 etc., comments are numbered with some bigger numbers (maybe relatively to the total posts in forum?), like #7 instead of #2, #8 instead of #3.

**Comment by 810** [comment]
This are the real id's, But I have improved the code. He is getting the message nummer, from the kunena config setting.
