### ISSUE TITLE
Discuss: Wrong place for "Comment added" message

### ISSUE THREAD

**Issue by chang-zhao** [Kunena/Kunena-Addons#157]
When Kunena-Discuss comment is added (e.g. in the article view), the message about Comment added appears in the top of the page (over all the content), as common system messages are set in Joomla.
That's not convenient.
Please, could we have Discuss messages appear just over the Reply form?

**Comment by 810** [comment]
For now we use the joomla system messages, maybe if we switch to full ajax, then we can reorder the message. Until then i will close this issue
