### ISSUE TITLE
Discuss and Kunena uses not the same setting for publish

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Addons#161]
Kunena Configuration / Security /
Public read and write = Yes

the second choose
Guest moderating: Yes

But over the Discuss Plugin, the comments directly published without moderate.
http://www.kunena.org/forum/k-3-0-kunena-discuss-p/129181-kunena-discuss-don-t-use-the-kunena-publishing-rights

**Comment by 810** [comment]
should be fixed now
