### ISSUE TITLE
Error when editing frontpage articles while Kunena Discuss is enabled.

### ISSUE THREAD

**Issue by Jiminimonka** [Kunena/Kunena-Addons#162]
See http://www.kunena.org/forum/kunena-3-0-support/129068-kunena-discuss-plugin-breaks-rockettheme-template#150175 and http://www.kunena.org/forum/kunena-3-0-support/129068-kunena-discuss-plugin-breaks-rockettheme-template#152789

**Comment by 810** [comment]
Is this still happening? because its was a bug on jomsocial, and they have fixed it.

**Comment by 810** [comment]
Closed by 3th party fix
