### ISSUE TITLE
3.0.7 still no category images guys...

### ISSUE THREAD

**Issue by smokedawg17** [Kunena/Kunena-Addons#170]
I love kunena but tis so damn ugly!!!!!!!!!!!!! Plz let us add some images for category... Rockettheme has made kunena look so cool you guys should look at there site. Dont mind me dropping by and hating a little =) you guys are awesome

**Comment by 810** [comment]
Hi we have working on it. K4.0 will have a bootstrapped template and will have the option to use icomoon icons.

I'm closing this issue because wrong section, this is addons.

**Comment by smokedawg17** [comment]
You guys are awesome!
