### ISSUE TITLE
Kunena Latest - Jump to last post

### ISSUE THREAD

**Issue by betteryouthanme** [Kunena/Kunena-Addons#174]
Since 3.1.0, if you click on a post of the module it forwards you to the first post of the topic instead of the last one.

This happens with the setting "Latest Topics" in module output.

**Comment by rich20** [comment]
Confirmed. This bug exists only with Blue Eagle, not with Crypsis.

**Comment by 810** [comment]
this has always been this way. but I have changed it.

**Comment by rich20** [comment]
No, with Kunena Latest 3.0.1 you jump to the last post.
