### ISSUE TITLE
Language files in russian is bad and corupt

### ISSUE THREAD

**Issue by romanown** [Kunena/Kunena-Addons#177]
Language files in russian in modules version 3.1 and 3.1.1, example latest, have unknoun simbols. It is in notepad++ view as DX1? DX0?.
example copy-past from editor 
MOD_KUNENALATEST_NO_MESSAGE="пет ѿообщений длѿ показа"
need MOD_KUNENALATEST_NO_MESSAGE="Нет сообщений для показа"
in the site view as MOD_KUNENALATEST_NO_MESSAGE="�?ет �?ообщений дл�? показа"
 In modules version 3.0 is good.

**Comment by 810** [comment]
I did the fix in K3.1.1 in the lasted module.:
See: https://github.com/Kunena/Kunena-Addons/blob/master/modules/kunenalatest/language/ru-RU/ru-RU.mod_kunenalatest.ini#L18

**Comment by romanown** [comment]
thank You

**Comment by romanown** [comment]
link on http://www.kunena.org/download for latst modul is right, but files downloaded is also bad. and other modules downloads is old bad files.
