### ISSUE TITLE
Latest Module: Topic title should not be used as class

### ISSUE THREAD

**Issue by severdia** [Kunena/Kunena-Addons#193]
For some reason, the topic title is used as the class in the Kunena Latest module and this can break some things. See attached screenshot.

![screen shot 2016-03-29 at 9 05 08 pm](https://cloud.githubusercontent.com/assets/355924/14132631/dc75eaa2-f5fc-11e5-82ba-f3af621d35b8.png)

**Comment by sozzled** [comment]
Yes, you're right.  That's not right.

**Comment by 810** [comment]
fixed
