### ISSUE TITLE
Kunena Latest module doesn't work with Kunena 5 beta4

### ISSUE THREAD

**Issue by Sulpher** [Kunena/Kunena-Addons#194]
Updated Kunena from 4.0.10 to K5.0.0-BETA4. As a result, I get the following error:
0 Call to a member function get() on string 
If to disable Kunena Latest module - forum works.

Entries from error.log:

> [Wed May 11 12:42:08 2016] [warn] [client 177.233.9.315] mod_fcgid: stderr: PHP Fatal error:  Call to a member function get() on a non-object in /var/modules/mod_kunenalatest/tmpl/default.php on line 12, referer: http://mysite.com/index.php/welcome-mat/2-long-discussion-and-off-topic?limitstart=0

> [Wed May 11 12:48:50 2016] [warn] [client 177.233.9.315] mod_fcgid: stderr: PHP Notice:  Undefined property: KunenaViewTopics::$params in /var/modules/mod_kunenalatest/tmpl/default.php on line 12, referer: http://mysite.com/index.php/welcome-mat/2-long-discussion-and-off-topic?limitstart=0

> [Wed May 11 12:50:11 2016] [warn] [client 177.233.9.315] mod_fcgid: stderr: PHP Notice:  Undefined property: KunenaViewTopics::$params in /var/modules/mod_kunenalatest/tmpl/default.php on line 12, referer: http://mysite.com/index.php/welcome-mat/2-long-discussion-and-off-topic?start=42

TECHNICAL INFORMATION:
Joomla 3.5.1
Kunena 5.0.0-BETA4.
Latest Module 3.1.2.1
PHP 7.0.6

**Comment by 810** [comment]
fixed on https://github.com/Kunena/Kunena-Forum/pull/3932
