### ISSUE TITLE
Many language files are broken in all extensions

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Addons#200]
https://www.kunena.org/forum/77-General-Talk-about-Kunena/138055-congratulation-with-new-site?start=10#178178
This error exists already long time.
Example language zh-TW
The language files are correct on Transifex and also here at Git.

Here a broken ini file if you download the extension from our download page:
![bildschirmfoto vom 2016-08-07 15-22-35](https://cloud.githubusercontent.com/assets/888847/17462761/b34bbf9a-5cb7-11e6-90da-3c9239bc29b9.png)
When I create an installation package from here, then the files are correct. Which action produces the error then?
![bildschirmfoto vom 2016-08-07 15-38-41](https://cloud.githubusercontent.com/assets/888847/17462778/f04f6130-5cb7-11e6-87ce-5693ce27f816.png)

**Comment by 810** [comment]
is already a issue open for this
