### ISSUE TITLE
Kunena Login 404 Error

### ISSUE THREAD

**Issue by betteryouthanme** [Kunena/Kunena-Addons#227]
Always get an "404 Component not found." - Error if i try to login via Kunena module.

Tested with
Kunena 5.0.3
Joomla 3.6.3
Kunena Login 5.0.1
and both kunena templates

//edit
happens only if the module is puplished on another page (not forum).

**Comment by 810** [comment]
this i because the secuirty measure on kunena, please set "Direct Component Access" to yes on kunena configurations

**Comment by betteryouthanme** [comment]
Yes now it works.
Is this the only way?

"Disabling this feature improves SEO and brings some protection against spam bots."
makes me think twice to enable Direct Component Access.

**Comment by 810** [comment]
i have tried to get it working, but until now i didn;t found any solution for it. still looking for a way.

ps there is already a
