### ISSUE TITLE
Kunena Latest : Module Output = Latest Posts shows only own posts

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Addons#245]
https://www.kunena.org/forum/36-German/139267-kunena-latest-modul-zeigt-nur-noch-eigene-beitr%C3%A4ge

Module Output = Latest Posts
the rest is default setting

You see on the image the difference. Both users are logged in at the same time.
![bildschirmfoto vom 2016-12-02 18-06-56](https://cloud.githubusercontent.com/assets/888847/20843316/2adc0330-b8bb-11e6-9678-beef6cae1f8a.png)

**Comment by 810** [comment]
So you see your own avatar?

**Comment by rich20** [comment]
Yes, I see only the own avatar and also only topics with my own messages.
