### ISSUE TITLE
Discuss: content article id set to topic id when discussion present

### ISSUE THREAD

**Issue by Ruud68** [Kunena/Kunena-Addons#247]
Hi,
as described and investigated here: https://www.kunena.org/forum/kunena-discuss-p/139781-kunenadiscuss-messing-up-article-id-from-jinput-fix-included

Issue is that when Discuss is enabled and there is an active discussion, KunenaForum::display sets the view's article id to the topic id leading to unexpected results with other plugins and modules on the article plage.

In the last (3) post there is a working work-around.

**Comment by Ruud68** [comment]
anyone?

**Comment by 810** [comment]
fixed, thnx
