### ISSUE TITLE
Login Module | It lacks in all language files the string MOD_KUNENALOGIN_DIRECT

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Addons#248]
It's this fix. https://github.com/Kunena/Kunena-Addons/pull/242
MOD_KUNENALOGIN_DIRECT="Please set <em><strong>Direct Component Access</strong></em> to <em><strong>Yes</strong></em> for using Kunena Login Module. On the Kunena Configurations."

It should be also included in all other languages.

**Comment by 810** [comment]
ok the translation was still set on master branch, so the old version.

I have updated it now, now we need to wait for transifex picks the new translation files.
