### ISSUE TITLE
Kunena Latest Module 5.0.3

### ISSUE THREAD

**Issue by chigolberi** [Kunena/Kunena-Addons#265]
The maximum length of the title theme does not work.
![1](https://user-images.githubusercontent.com/30241824/28318207-9636efd0-6bd2-11e7-894a-93cecb2ddf02.jpg)

**Comment by mc-hovanskiy** [comment]
I confirm. Not working.

**Comment by chigolberi** [comment]
Please fix the bug

**Comment by 810** [comment]
is fixed, will be on the next version

**Comment by chigolberi** [comment]
Thank you friend!!!
