### ISSUE TITLE
Discuss plugin start new topic on each visit

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Addons#280]
https://www.kunena.org/forum/kunena-discuss-p/153128-discuss-plugin-start-new-topic-on-each-visit-and-wrong-title-per-message

1. Plugin setting Create Topic on = First Visit
2. Create a article to discuss
3. Go to the article and refresh the page several times
4. Go in the forum to recent topics

The plugin has created several new topics (the same number as you've refreshed the article). Each visit creates a new Kunena topic.

Notice: Plugin  setting Create Topic on = First Reply
You can't use this as workaround, then if you reply on the article page, it creates also at each replies a new Kunena topic.

**Comment by 810** [comment]
[KunenaDiscuss debug: createReference: Error:exception 'JDatabaseExceptionExecuting' with message 'Duplicate entry '33' for key 'PRIMARY'' in /home/dagblad/domains/newf1.nl/public_html/libraries/joomla/database/driver/mysqli.php:650 Stack trace: #0 /home/dagblad/domains/newf1.nl/public_html/plugins/content/kunenadiscuss/kunenadiscuss.php(959): JDatabaseDriverMysqli->execute() #1 /home/dagblad/domains/newf1.nl/public_html/plugins/content/kunenadiscuss/kunenadiscuss.php(1078): plgContentKunenaDiscuss->createReference(Object(stdClass), NULL) #2 /home/dagblad/domains/newf1.nl/public_html/plugins/content/kunenadiscuss/kunenadiscuss.php(768): plgContentKunenaDiscuss->createTopic(Object(stdClass), Object(KunenaForumCategory), 'blog 2') #3 /home/dagblad/domains/newf1.nl/public_html/plugins/content/kunenadiscuss/kunenadiscuss.php(475): plgContentKunenaDiscuss->showPlugin(2, false, Object(stdClass), false) #4 /home/dagblad/domains/newf1.nl/public_html/plugins/content/kunenadiscuss/kunenadiscuss.php(190): plgContentKunenaDiscuss->prepare('com_content.cat...', Object(stdClass), Object(Joomla\Registry\Registry)) #5 [internal function]: plgContentKunenaDiscuss->onContentBeforeDisplay('com_content.cat...', Object(stdClass), Object(Joomla\Registry\Registry), 0) #6 /home/dagblad/domains/newf1.nl/public_html/libraries/joomla/event/event.php(70): call_user_func_array(Array, Array) #7 /home/dagblad/domains/newf1.nl/public_html/libraries/joomla/event/dispatcher.php(160): JEvent->update(Array) #8 /home/dagblad/domains/newf1.nl/public_html/components/com_content/views/category/view.html.php(116): JEventDispatcher->trigger('onContentBefore...', Array) #9 /home/dagblad/domains/newf1.nl/public_html/libraries/src/MVC/Controller/BaseController.php(672): ContentViewCategory->display() #10 /home/dagblad/domains/newf1.nl/public_html/components/com_content/controller.php(113): Joomla\CMS\MVC\Controller\BaseController->display(true, Array) #11 /home/dagblad/domains/newf1.nl/public_html/libraries/src/MVC/Controller/BaseController.php(710): ContentController->display() #12 /home/dagblad/domains/newf1.nl/public_html/components/com_content/content.php(43): Joomla\CMS\MVC\Controller\BaseController->execute(NULL) #13 /home/dagblad/domains/newf1.nl/public_html/libraries/src/Component/ComponentHelper.php(382): require_once('/home/dagblad/d...') #14 /home/dagblad/domains/newf1.nl/public_html/libraries/src/Component/ComponentHelper.php(357): Joomla\CMS\Component\ComponentHelper::executeComponent('/home/dagblad/d...') #15 /home/dagblad/domains/newf1.nl/public_html/libraries/src/Application/SiteApplication.php(194): Joomla\CMS\Component\ComponentHelper::renderComponent('com_content') #16 /home/dagblad/domains/newf1.nl/public_html/libraries/src/Application/SiteApplication.php(233): Joomla\CMS\Application\SiteApplication->dispatch() #17 /home/dagblad/domains/newf1.nl/public_html/libraries/src/Application/CMSApplication.php(195): Joomla\CMS\Application\SiteApplication->doExecute() #18 /home/dagblad/domains/newf1.nl/public_html/index.php(49): Joomla\CMS\Application\CMSApplication->execute() #19 {main} ]

**Comment by 810** [comment]
fixed on nightly build.
