### ISSUE TITLE
Kunena Latest and php 7.3 | Compilation failed: invalid range in character class at offset 18

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Addons#282]
https://www.kunena.org/forum/general-questions-and-how-tos/156737-php-7-3-and-leatest-post-module-is-show-nothing

If you use PHP 7.3 you get this error:
Warning: preg_replace_callback(): Compilation failed: invalid range in character class at offset 18 in /.../components/com_kunena/views/topics/view.html.php on line 203

**Comment by xillibit** [comment]
How do-you do to reproduce this issue ?

**Comment by rich20** [comment]
I don't know with which php 7.3 version I've tested in those days. But now with php 7.3.6 (Joomla 3.9.12-dev and Kunena 5.1.14 as well 5.1.15-dev) I see no error anymore.

**Comment by xillibit** [comment]
Fixed now in Kunena 5.2
