### ISSUE TITLE
[Kunena Latest v6.0.0-Beta-DEV] Class 'Kunena\Forum\Site\View\topics\HtmlView' not found

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Addons#291]
You get this error on assigned pages

Call stack
--
# | Function | Location
1 | () | JROOT/libraries/kunena/src/Forum/KunenaForum.php:511
2 | Kunena\Forum\Libraries\Forum\KunenaForum::display() | JROOT/modules/mod_kunenalatest/class.php:108
3 | ModuleKunenaLatest->_display() | JROOT/libraries/kunena/src/Module/KunenaModule.php:112
4 | Kunena\Forum\Libraries\Module\KunenaModule->display() | JROOT/modules/mod_kunenalatest/mod_kunenalatest.php:39
5 | include() | JROOT/libraries/src/Dispatcher/ModuleDispatcher.php:54
6 | Joomla\CMS\Dispatcher\ModuleDispatcher::Joomla\CMS\Dispatcher\{closure}() | JROOT/libraries/src/Dispatcher/ModuleDispatcher.php:57
7 | Joomla\CMS\Dispatcher\ModuleDispatcher->dispatch() | JROOT/libraries/src/Helper/ModuleHelper.php:295
8 | Joomla\CMS\Helper\ModuleHelper::renderRawModule() | JROOT/libraries/src/Helper/ModuleHelper.php:167
9 | Joomla\CMS\Helper\ModuleHelper::renderModule() | JROOT/libraries/src/Document/Renderer/Html/ModuleRenderer.php:102
10 | Joomla\CMS\Document\Renderer\Html\ModuleRenderer->render() | JROOT/libraries/src/Document/HtmlDocument.php:710
11 | Joomla\CMS\Document\HtmlDocument->countModules() | JROOT/templates/cassiopeia/index.php:109
12 | require() | JROOT/libraries/src/Document/HtmlDocument.php:783
13 | Joomla\CMS\Document\HtmlDocument->_loadTemplate() | JROOT/libraries/src/Document/HtmlDocument.php:842
14 | Joomla\CMS\Document\HtmlDocument->_fetchTemplate() | JROOT/libraries/src/Document/HtmlDocument.php:645
15 | Joomla\CMS\Document\HtmlDocument->parse() | JROOT/libraries/src/Application/CMSApplication.php:1025
16 | Joomla\CMS\Application\CMSApplication->render() | JROOT/libraries/src/Application/SiteApplication.php:802
17 | Joomla\CMS\Application\SiteApplication->render() | JROOT/libraries/src/Application/CMSApplication.php:284
18 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/includes/app.php:63
19 | require_once() | JROOT/index.php:32

**System information**
- Joomla version: 4.1.1-dev
- Joomla template: CASSIOPEIA
- Kunena version: 6.0.0-RC2-DEV-GIT
- Kunena template: Aurelia
- Php version: 7.4.28 
- Database version: 10.5.11-MariaDB

**Desktop**
- OS: Ubuntu 20.04.2 LTS
- Browser: Chromium, Firefox and Opera

**Comment by mahagr** [comment]
To me it looks like Topics is written wrong (autoloader in Linux is case sensitive).
