### ISSUE TITLE
[Kunena Latest v6.0.0-Beta-DEV] Error in the K-Latest configuration

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Addons#292]
Instead of the option show all or nothing, it shows this error:

<br /><b>Warning</b>:  htmlspecialchars() expects parameter 1 to be string, array given in <b>/.../layouts/joomla/form/field/text.php</b> on line <b>99</b><br />
`<br /><b>Warning</b>:  htmlspecialchars() expects parameter 1 to be string, array given in <b>/.../layouts/joomla/form/field/text.php</b> on line <b>99</b><br />`
<br />
![Bildschirmfoto von 2022-03-07 14-50-20](https://user-images.githubusercontent.com/888847/157047525-dc7e4c1f-a4ca-4694-b3de-a0281ed96f3d.png)

**Comment by xillibit** [comment]
With my fix the error `Warning: htmlspecialchars() expects parameter 1 to be string, array given in` has disappear but i still don't won't why it don't load th list of Kunena categories
