### ISSUE TITLE
[Kunena Latest v6.0.0-Beta-DEV] Wrong route with K-Latest

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Addons#293]
(Issue edited and adjusted)
**To Reproduce**
Click on one of this link (see image).
![Bildschirmfoto von 2022-03-08 19-47-19](https://user-images.githubusercontent.com/888847/157306479-4b027b66-73ca-413e-afe5-70a5b10d5306.png)

**Result**
The URL shows ...**/component/kunena**/ in the address
If you have disabled in the configuration Direct Component Access, you get this error:

**404 Component not found.**

Call stack
--
# | Function | Location
1 | () | JROOT/components/com_kunena/src/Dispatcher/Dispatcher.php:226
2 | Kunena\Forum\Site\Dispatcher\Dispatcher->checkAccess() | JROOT/components/com_kunena/src/Dispatcher/Dispatcher.php:59
3 | Kunena\Forum\Site\Dispatcher\Dispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:389
4 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/SiteApplication.php:204
5 | Joomla\CMS\Application\SiteApplication->dispatch() | JROOT/libraries/src/Application/SiteApplication.php:243
6 | Joomla\CMS\Application\SiteApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:278
7 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/includes/app.php:63
8 | require_once() | JROOT/index.php:32

</div>

**Comment by pippo8765** [comment]
+1

**Comment by rich20** [comment]
This issue still exists with K-Latest 6.0.2
