### ISSUE TITLE
[Kunena Latest v6.0.0] Category selection is not possible

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Addons#304]
https://www.kunena.org/forum/36-German/167029-kunena-latest,-kategoriefilter-funktioniert-nicht
Confirmed

Depending on whether Show categories or Hide categories is selected, either all categories will be shown or all will be hidden. Selecting individual categories does not work.
.
![Bildschirmfoto vom 2022-10-23 03-17-48](https://user-images.githubusercontent.com/888847/197368550-ce818581-6ea7-42cc-9d89-57d42e03847b.png)

**Comment by xillibit** [comment]
I have a found for that, but the isse then it will change the items displayed in recent discussions page.  If you og to the forum directly by the menu forum you will see the same items tan before but if you click on menu recent discussions you will see just some items depending on the categories settings défined in the menu recent discussions
