### ISSUE TITLE
[PHP 8.2] Kunena Discuss :  Deprecated: Creation of dynamic property...

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Addons#310]
You get this error on the article page:

Deprecated: Creation of dynamic property PlgContentKunenaDiscuss::$ktemplate is deprecated in /.../plugins/content/kunenadiscuss/kunenadiscuss.php on line 219

**System information**
- Joomla version: ‎4.4.1
- Joomla template: CASSIOPEIA
- Kunena version: 6.2.1-DEV
- Kunena template: Aurelia
- Php version: 8.2.9
- Database version: 10.5.22-MariaDB

**Desktop**
- OS: Ubuntu 22.04.1 LTS
- Browser: Chromium, Firefox and Opera

**Comment by xillibit** [comment]
It has been fixed here some time ago : https://github.com/Kunena/Kunena-Addons/commit/4ecb513223c1e247fa7c7b812dc6244b92764cec, i need to make a new release

**Comment by rich20** [comment]
ok, it works with this fix
