### ISSUE TITLE
Using deprecrated classdeprecated 'isAdmin()' in Kunena discuss returns errors in all admin menus

### ISSUE THREAD

**Issue by joomlafun** [Kunena/Kunena-Addons#320]
After activating kunena discuss that I downloaded from the official download page where it is advertised as joomla 5 compatible I get :
 
"0 Call to undefined method Joomla\CMS\Application\AdministratorApplication::isAdmin() 
 /plugins/content/kunenadiscuss/kunenadiscuss.php:90 		"
```
// Do not register plug-in in administration.
		if ($this->app->isAdmin())
```

isSite() and isMenu() are also deprecated since joomla 3.8 if I'm not wrong?

**Comment by joomlafun** [comment]
You may try replacing 
    isSite() with isClient('site'), and
    isAdmin() with isClient('admin').

**Comment by xillibit** [comment]
Are-you using the 6.0.5 version Kunena discuss plugin ?

**Comment by joomlafun** [comment]
Hi, somehow I thought I downloaded the 6.05 but I downloaded the 5.22

**Comment by joomlafun** [comment]
Sorry, I don't know why I picked the older versions at the bottom of the page :s
